### ISSUE TITLE
Settings does not open

### ISSUE THREAD

**Issue by CorvetteCole** [Pobega/gnome-shell-extension-mullvad-indicator#11]
## Issue Description:
Open panel containing the mullvad icon, attempt to click settings. Settings cannot be opened. See error below

The settings of extension mullvadindicator@pobega.github.com had an error:
```
GLib.FileError: Failed to open file “prefs.ui”: No such file or directory
```

Stack trace:
```
buildWidget@/home/coleg/.local/share/gnome-shell/extensions/mullvadindicator@pobega.github.com/prefs.js:16:23
buildPrefsWidget@/home/coleg/.local/share/gnome-shell/extensions/mullvadindicator@pobega.github.com/prefs.js:54:24
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

## System information:
Gnome 3.36

## Extension version:
Latest from extensions.gnome.org

**Comment by Pobega** [comment]
This is already fixed, see: https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/issues/8

I'm going to push the update to e.g.o. this weekend, in the meantime you can fix it locally using the diff here; https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/pull/9/commits/72b537e6b20e9de164a1c68f3ed6a373038db952
