### ISSUE TITLE
Make the Mullvad info a standalone feature

### ISSUE THREAD

**Issue by dosenfleisch** [Pobega/gnome-shell-extension-mullvad-indicator#16]
## Feature Description:
Your extension basically duplicates the existing Ubuntu drop down menu and if the mullvad icon is added to the top bar, that becomes clear.  The Mullvad info is yet another click away.  A dedicated drop down showing the Mullvad connection information from the top bar, without all the shutdown/network/etc duplication would be more usable.  Wouldn't that be easier for you to do?  You can do better than I can, but in my mind, one click is better than two.  Otherwise good job, it works.

**Comment by Pobega** [comment]
Could you elaborate what you mean by this? Perhaps draft some screenshots of exactly what you mean.

**Comment by dosenfleisch** [comment]
[Bildschirmfoto von 2021-02-07 09-20-51.png]
With the extension's settings "display indicator icon" set to on, whether you click on the shut down icon or the Mullvad Icon, you get the same result, the same submenu, both of which have another Mullvad icon that needs to be clicked on to see the connection details. So, there is a rather annoying duplication of shutdown menus just to gain access to Mullvad connection details.

[Bildschirmfoto von 2021-02-07 09-23-50.png]

With the extension's settings "display indicator icon" set to OFF, no Mullvad icon appears except a level deeper in the shut down menu. Nothing in the tray. But the duplication of shutdown menus is reduced to one instance. The trouble with this is that there is no indication that there is a Mullvad extension even available unless you know it is there already and click on the only instance of a shut down menu to find it.

My suggestion was to show a single Mullvad icon in the tray, with the the dropdown showing only the connection details that users expected to see when they installed the extension. That is please don't bury the extension in the shutdown menu, then again in a submenu.

Look, you've done a great job. The extension works flawlessly and I can't say the same for many many other extensions I've tried that won't even work let alone not crash the computer.
I use Mullvad and I don't like having the app up on the deskotp. I'd rather have a simple one click tray icon to show me what server I'm connected to. This I'd find very useful. Sorting through the temporary confusion of duplicate shutdown menus to find Mullvad server details buried two levels deeper wasn't a deal breaker, but for many, this would be one click too many.

No criticism intended, it's just how I find it and if my suggestion helps, more users would find it useful. As would I. Thanks.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Samstag, 6. Februar 2021 13:11 schrieb Michael Pobega <notifications@github.com>:

**Comment by Pobega** [comment]
I think your screenshots didn't attach properly so I'm still a bit confused about the suggestion, sorry.

If I'm understanding correctly what you want though, there is an earlier version that was a tray icon with it's own popout rather than integrated with the Gnome system tray. IIRC you could try that out at commit 7ba751535bfe9520dd8f2c72814cb1688838b71d I believe.

The 'reason' for it being the way it is now is just to integrate smoothly and feel like a Gnome-native application. The primary use case (at least during design) was just to have the icon in the tray to let you know if/when you get disconnected from your VPN.

And don't worry, I'm not offended, criticism is great. I'm just trying to understand exactly what you're asking for.

**Comment by dosenfleisch** [comment]
I believe you got the point already. I'll check out your link. As for the photos I'd attached, they were embedded, but also attached separately. I don't know why you had the difficulty, nevertheless, unembedded, I've attached them again.
Thanks,
P

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Sonntag, 7. Februar 2021 10:17 schrieb Michael Pobega <notifications@github.com>:

**Comment by Pobega** [comment]
I believe the screenshots are being lost because Github doesn't seem to properly support email attachments. Please attach them at https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/issues/16 via the web interface

**Comment by Pobega** [comment]
I believe this is fixed in the current release by https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/issues/21
