### ISSUE TITLE
Connection state issues with Fedora 35 and 36

### ISSUE THREAD

**Issue by zoktiik** [Pobega/gnome-shell-extension-mullvad-indicator#22]
## Issue Description:

Both on a machine running F35 and a machine running F36, the indicator cannot detect a connection at all. Whether the GUI is open or closed, whether connected or disconnected, the indicator is dark despite any attempts to refresh. All Mullvad Indicator options are the defaults (on). 
I also tried disabling every other extension, in case there could be a conflict, and the issue continues to persist.

## System information:

F35 machine is an install that I've had for some months, and the F36 machine is an install that I set up just a couple of days ago. On at least the F36 machine, I do not have any other DEs installed.

Distro: Fedora Linux 36 (and 35) Workstation Edition
GNOME Version: 42.4 (and 41.6)
Mullvad app version: 2022.4

## Extension version:

Version 5, on both machines. Installed from extensions.gnome.org.

**Comment by Pobega** [comment]
Is `https://am.i.mullvad.net/json` working for you? [That's what is used to test whether or not you're connected to Mullvad](https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/blob/master/mullvad.js#L99)

Note that I no longer personally use this extension (or have an active Mullvad subscription) so it could definitely be broken. If you're interested in trying to debug you could poke around there, if the connection info is working fine then the icon update code is probably not working.

**Comment by zoktiik** [comment]
> Is `https://am.i.mullvad.net/json` working for you?

That is working. And at first, so was the extension on my F36 machine this boot. It was correctly showing the first server that the daemon had auto-connected to. Upon switching relays, the extension updated again to show the new connection info. But after trying to switch to a third relay, the extension didn't update at all, showing the second relay. Only when disconnecting from Mullvad and reconnecting did the extension's system menu item update to reflect the current connection. 

This appears to be a reproducible issue with switching servers, where it will only show the first or second server's connection info. `https://am.i.mullvad.net/json` always gives me the correct info for my current connection. I am using the command line `mullvad` app to perform all operations.

I need to do some more testing to see if I can reproduce the original issue, although the two seem like they could still be related to each other.

**Comment by Pobega** [comment]
There is an option for 'Automatic refresh time' in the extension settings. You could lower this if you wanted, though that would mean more polling of Mullvad.

It basically exists as a 'nuclear' option for forcing a refresh every so often. The application operates on a timeout but can be interrupted by network monitor signals, this option controls the timeout.

**Comment by Pobega** [comment]
@zoktiik is this issue still relevant? Curious if it's happening with recent extension releases.

**Comment by Pobega** [comment]
I'm going to mark this as closed since I can't repro it after resubbing to Mullvad to polish the Gnome 45 port and attempting to reproduce this issue. The extension seems to work as expected, and I imagine this may have been either a network or configuration issue.

If this issue still persists feel free to comment and I can re-open.
