### ISSUE TITLE
Please update for Gnome 43

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [Pobega/gnome-shell-extension-mullvad-indicator#23]
## Feature Description:

Please update the extension for Gnome 43.

Thank you!

**Comment by no-comma** [comment]
I'm working on porting the extension to GNOME 43, I'll create a PR once it's done.

**Comment by Pobega** [comment]
Submitted for approval: https://extensions.gnome.org/review/38865

I expect to get some feedback on a few things I skipped from a review of a fork, but I can handle those when they come in (it's also possible they're a little more lenient on already existing extensions getting updates, so who knows.)

Thank you @no-comma ,  keeping the extension up-to-date with Gnome always feels like a cat and mouse game. I wish there was a world in which every Gnome release didn't completely break extensions.

**Comment by Pobega** [comment]
Closing this since the update was accepted upstream
