### ISSUE TITLE
GLib.FileError: Failed to open file “prefs.ui”: No such file or directory

### ISSUE THREAD

**Issue by yochananmarqos** [Pobega/gnome-shell-extension-mullvad-indicator#8]
Mullvad Indicator v2 installed from GNOME Extensions
GNOME 3.36.6
Manjaro Linux

I receive this error when attempting to open the extension settings:

The settings of extension mullvadindicator@pobega.github.com had an error:
```
GLib.FileError: Failed to open file “prefs.ui”: No such file or directory
```

Stack trace:
```
buildWidget@/home/yochanan/.local/share/gnome-shell/extensions/mullvadindicator@pobega.github.com/prefs.js:16:23
buildPrefsWidget@/home/yochanan/.local/share/gnome-shell/extensions/mullvadindicator@pobega.github.com/prefs.js:54:24
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Pobega** [comment]
Do you have a `prefs.ui` file in `~/.local/share/gnome-shell/extensions/mullvadindicator@pobega.github.com`?

Also out of curiosity (I should add it to the issue format here) are you using the extensions.gnome.org release or Git?

**Comment by yochananmarqos** [comment]
Yes, there is a `prefs.ui`. 

I would have also tried from the latest commit, but it appears the extension release is the same.

**Comment by Pobega** [comment]
@yochananmarqos Could you try the `ui-file-fix` branch I just pushed? I wonder if for some reason you need the full path on your system.

https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/tree/ui-file-fix

**Comment by yochananmarqos** [comment]
That fixed it!

**Comment by Pobega** [comment]
Great, thanks for testing it! I'll push an update to e.g.o. as soon as I get an opportunity.
